### ISSUE TITLE
Generate entry spreadsheets, tabs for TD

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#163]
Here are a few that I noticed missing. I figured best to create from automation versus me manually adding. 

- [x] generate 2017 and 2018 crop yield sheets for BATH_R; only 2016 exists. Rotations stated here: 
https://docs.google.com/spreadsheets/d/1CZJVPVXghb3fJFKl7BKUrH9JOlIuGoCC8krtJQLfw84/edit#gid=0 

- [x] generate tile flow (WAT1) and irrigation water inflow (WAT17) sheets for BATH_R. Only crop and soil exist now. In the master sheet, tile nitrate and water table are not marked so assuming that is not being collected and therefore don’t need those sheets.  
https://drive.google.com/drive/folders/0B6ZGw0coobCxR0g1R25Wd2RqNnc

- [x] remove AGR56 from HICKS_B spreadsheets for 2015-2018 (https://docs.google.com/spreadsheets/d/1Gjh4rT0QGusUg53vxtzVvNuSWdnAUWxcjeotVAMHxgE/edit#gid=828255805). It is already NOT marked in MASTER sheet. 

- [x] need 2016 sheet added for tile flow (WAT1) at SWROC. The master sheet and other water sheets have 2016 in them. 
https://docs.google.com/spreadsheets/d/1CIw345UztORlCVCthF34u21cr8kjaPoZzTUVN9d_bFg/edit#gid=1441867990 

- [x] need irrigation water inflow (WAT17) sheet for SWROC created. 

- [x] need tile flow (WAT1) and water quality (WAT20) for HICKS_S created. These are marked YES in the master sheet for 2018. https://drive.google.com/drive/u/0/folders/0B6ZGw0coobCxSGhlQy1kWWg0MEE?ths=true

- [x] add tab for 2018 in HICKS_P water table spreadsheet: https://docs.google.com/spreadsheets/d/1d2wlQpujw1i91brykn7eszFILOwhvIUrVRZTVJ65q3w/edit#gid=899245276

- [x] CROP spreadsheet not needed for HICKS_P. No data collected at all for any years. Nothing marked in the MASTER for agronomic data. Delete. 
https://drive.google.com/drive/u/0/folders/0B6ZGw0coobCxdXdxeUhJcEtCM1U?ths=true 

- [x] create soil moisture (SOIL5) tab in SOIL spreadsheet for HICKS_S and SWROC. Nothing exists right now whereas the tab exists for HICKS_P etc within the soil sheet. 
https://docs.google.com/spreadsheets/d/1a_4sc1VbnQidOxDUHIubhQhvZeseLf82J-NZJnsyR5A/edit#gid=1796483440
https://docs.google.com/spreadsheets/d/1KB9fcB4Pld4125VEoO5kRuSibZEUjimJ4xboOYRvec4/edit#gid=1796483440

**Comment by giorgichi** [comment]
> need irrigation water inflow (WAT17) sheet for SWROC created.

Irrigation information is entered into the MANAGEMENT form. See the "Irrigation" tab in the backend sheet.

**Comment by giorgichi** [comment]
Usually, soil moisture data is sent to Daryl to add to the database. Tabs in the google sheets are temporary and normally includes low resolution (aggregated) data.

**Comment by loriabendroth** [comment]
@giorgichi this is fine about soil moisture. I had posted this b/c it looked like it was handled differently across sites - in terms of sometimes a sheet existing for them to populate into and other times not. 
I had populated red text with a note about hyperlink coming soon into SS for sites so they knew where to put data. Can you go into SS and change this red text/hyperlink accordingly with your changes made here? Go to report "TD All Sites (Unchecked)" and scroll down right hand column for these.

**Comment by giorgichi** [comment]
@loriabendroth, you are correct - soil moisture data is not treated uniformly across the sites. The main reason is that soil moisture has been differently measured and/or reported at each site. Unlike CSCAP there is no common protocol in place, for obvious reasons. As a result, I have been trying different ways to accommodate those differences. For example, if soil moisture is measured manually every so often, I encourage to upload data to a corresponding Google Sheet. On the other hand, if we are getting continuously measured soil moisture data with 5 min intervals than it should be uploaded as CSV or TXT file because Google Sheets do not handle well long data. Occasionally some PIs provide only daily (supposedly aggregated) soil moisture data, which can be added as CSV/TXT or copied into the Google Sheet. Both can work in this case. For some sites, I only know that soil moisture was measured or is going to be measured - with no additional details. In those cases, I prefer to wait to PIs readiness to provide their data before adding any standard sheet and directing them to it. 

In any case, all soil moisture data, despite their origins, are combined and send to Daryl to add to TD db.  I hope this explains some of the hurdles we face with soil moisture data, not to mention problems associated with a diversity of formats the data comes.

**Comment by giorgichi** [comment]
@loriabendroth - I added soil moisture tab for HICKS_S. I did not find other site with **red text/hyperlink** for SOIL MOISTURE in SS.

**Comment by loriabendroth** [comment]
I have addressed remaining red items in SS with needed hyperlinks for users.
