### ISSUE TITLE
Populate site pictures for data website

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#280]
@giorgichi , for the TD external website:

- [x] Populate 10-15 photos per site to Photos folders from those uploaded to internal Google drive. Select photos that show: whole field, plot level, weather instrumentation, drainage instrumentation, installation (if exist), and crops grown. 
- [x] Recommend not selecting photos that have people in them. But if you do, email the person and make sure they are OK with it. 
- [x] Label photos uniformly, see example of Sus Corn. https://datateam.agron.iastate.edu/cscap/dl/

**Comment by giorgichi** [comment]
@loriabendroth  There are three sites (FULTON, DEFI_R, VANWERT) that I have not uploaded photos for because they are mixed together. As I remember you were working on organizing them. If you have done it, could you share the sorted photos with me? 

Otherwise, I will leave them since I had to work on other more urgent TD tasks.

**Comment by loriabendroth** [comment]
yes, these photos can wait until next week as other items are more pressing. I wasn't planning on sorting the photos - didn't have that on my list.

**Comment by giorgichi** [comment]
Added the last three sites.

**Comment by loriabendroth** [comment]
@giorgichi , you selected great photos. I have looked at a few folders and they capture the sites well. That had to be a sloooow process. Thanks.
