### ISSUE TITLE
Change date structure

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#296]
@giorgichi , change date from mm/dd/yyyy to yyyy-mm-dd in following sheets. This is how management data and comments are formatted. It also is ISO 8601 standard so best approach. If want to discuss, please do here. 

- [ ] agronomic
- [ ] irrigation
- [ ] soil moisture
- [ ] soil_properties
- [ ] tile_flow and loads
- [ ] water_quality
- [ ] water_stage
- [ ] water_table
- [ ] weather

The following management tables need edited too but could wait until I have finished all edits to entries if want. 
- [ ] mngt_dwm_data
- [ ] mngt_fertilizer
- [ ] mngt_irrigation
- [ ] mngt_planting_harvest

**Comment by giorgichi** [comment]
@loriabendroth, `date` column in all tables have dates recorded in **yyyy-mm-dd** format. The most likely reason you seeing dates as **mm/dd/yyyy** is because of the default settings in your excel. To see true format of the data, you should open `.csv` file with **Notepad** or some other text editor.

P.S. implementation of ISO standards was discussed and agreed upon already: https://github.com/isudatateam/datateam/issues/22#issuecomment-538092394

**Comment by loriabendroth** [comment]
@giorgichi , yep you are correct. All are correct and a few I have found in comments, I have changed.
