### ISSUE TITLE
Check validity of "biomass yield"

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#368]
@giorgichi , biomass yield does not turn to black as an option even when all sites are selected. Should this variable be removed from the list? 
https://datateam.agron.iastate.edu/td/dl/#tab_data

**Comment by akrherz** [comment]
Within the `agronomic_data` database table, I find no `biomass_yield` column, which is what the UI expects in order to make that option available for selection. Here's the present columns in the `agronomic_data` table:

Column         |  Type   | Collation | Nullable | Default 
----------------------- | -------- | ----------- | ---------- | ---------
 siteid                 | text    |           |          | 
 plotid                 | text    |           |          | 
 location               | text    |           |          | 
 crop                   | text    |           |          | 
 trt_2                  | text    |           |          | 
 trt_value_2            | text    |           |          | 
 year                   | integer |           |          | 
 date                   | date    |           |          | 
 leaf_area_index        | real    |           |          | 
 final_plant_population | real    |           |          | 
 grain_moisture         | real    |           |          | 
 crop_yield             | real    |           |          | 
 standard_moisture      | text    |           |          | 
 whole_plant_biomass    | real    |           |          | 
 vegetative_biomass     | real    |           |          | 
 grain_biomass          | real    |           |          | 
 corn_cob_biomass       | real    |           |          | 
 forage_biomass         | real    |           |          | 
 whole_plant_total_n    | real    |           |          | 
 vegetative_total_n     | real    |           |          | 
 grain_total_n          | real    |           |          | 
 corn_cob_total_n       | real    |           |          | 
 vegetative_total_c     | real    |           |          | 
 grain_total_c          | real    |           |          | 
 corn_cob_total_c       | real    |           |          |

**Comment by giorgichi** [comment]
@loriabendroth @akrherz `biomass_yield` was renamed to `forage_biomass` during the final revision of the data dictionary (according to Lori's suggestion). You can find it listed in the table above. The agronomic table was also updated accordingly. Daryl should have the last version of all data (including Data Dictionary and Agr Data) in the database.

**Comment by loriabendroth** [comment]
@akrherz , can you move Forage Biomass to the center column under Plant and Grain Biomass. List it as the fifth item in list.
