### ISSUE TITLE
NN fertilizer management entries

### ISSUE THREAD

**Issue by loriabendroth** [isudatateam/datateam#408]
@skbowd , can you review the FertilizerName column, specifically "other" entries. Users have appended text at the end of other that I think can sometimes be categorized into our existing options and therefore, not need to be listed under Other. Would like to see if we can reduce some of the "Other" entries if possible through standardization.

**Comment by skbowd** [comment]
@loriabendroth @erwaring   There are only a couple changes we could make here......
1) We could change "superu" and "esn urea" to "urea" and they would just be differentiated by formula and/or stabilizer?
2) We could also change "10-34-4" and "19-17-0" to "other_starter" since the analysis would be represented in FertFormulation?
